### ISSUE TITLE
Code review - 2

### ISSUE THREAD

**Issue by rashedarman** [rashedarman/portfolio#8]
- You can use `height: 100%` on card elements in about section so it takes all available space stretched by other sibling elements
- You can use bootstrap `gap` classes for automatic space between flex childrens instead of manually setting margin on each elements. This will result in cleaner and more maintainable code.
- You should put corresponding ID of sections inside nav anchors so it moves to that particular section on clicking.

**Comment by Carl2678** [comment]
Good Job.
